project:
  type: book
  output-dir: ./publish

book:
  title: "AISecurity-Research-Template"
  language: "en"
  author: "Guangtao Zhang"
  reader-mode: true
  page-navigation: true
  navbar:
    collapse-below: lg
    right:
      - icon: github
        href: https://github.com/hardenedlinux/AISecurity-Research-Template
        aria-label: GitHub
    left:
      - text: "Overview"
        href: index.qmd

  chapters:
    - index.qmd

    - part: julia.qmd
      chapters:
        - julia-test.ipynb

    - part: python.qmd
      chapters:
        - python-test.ipynb

  # sidebar:
  # tools:
  #   - icon: github
  #     href: https://github.com/hardenedlinux/AISecurity-Research-Template
  #     text: AISecurity-Research-Template GitHub

format:
  # gfm:
  #   keep-yaml: true
  #   fig-format: svg
  #   wrap: preserve

  html:
    theme: [cosmo, style.css]
    code-overflow: wrap
    code-fold: true
    css: style.css
    link-external-icon: true
    link-external-newwindow: true

  pdf:
    # documentclass: ctexbook
    toc: true
    pdf-engine: tectonic
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}

execute:
  warning: false

biliography: references.lib
