project:
  type: book
  output-dir: ./publish

book:
  title: "AISecurity-Research-Template"
  language: "en"
  author: "Guangtao Zhang"
  reader-mode: true
  chapters:
    - index.qmd

    - julia.qmd
    - part: julia-test.ipynb

    - python.qmd
    - part: python-test.ipynb

format:
  # gfm:
  #   keep-yaml: true
  #   fig-format: svg
  #   wrap: preserve

  html:
    theme: cosmo
    code-fold: true

  pdf:
    # documentclass: ctexbook
    pdf-engine: tectonic

execute:
  warning: false

biliography: references.lib
