project:
  type: book
  output-dir: ./publish

book:
  title: "AISecurity-Research-Template"
  language: "en"
  author: "Guangtao Zhang"
  reader-mode: true
  page-navigation: true
  navbar:
    collapse-below: lg
    right:
      - icon: github
        href: https://github.com/hardenedlinux/AISecurity-Research-Template
        aria-label: GitHub
    left:
      - text: "Overview"
        href: index.qmd

  chapters:
    - index.qmd

    - julia.qmd
    - part: julia-test.ipynb

    - python.qmd
    - part: python-test.ipynb

  # sidebar:
    # tools:
    #   - icon: github
    #     href: https://github.com/hardenedlinux/AISecurity-Research-Template
    #     text: AISecurity-Research-Template GitHub

format:
  # gfm:
  #   keep-yaml: true
  #   fig-format: svg
  #   wrap: preserve

  html:
    theme: cosmo
    code-fold: true

  pdf:
    # documentclass: ctexbook
    toc: true
    pdf-engine: tectonic

execute:
  warning: false

biliography: references.lib
