data: {
  shape: page
  style.multiple: true
}
user: User {shape: person}
workflow: Workflow {
  tower: Cell Tower {
    satellites: {
      shape: stored_data
      style.multiple: true
    }

    satellites -> transmitter
    satellites -> transmitter
    satellites -> transmitter
    transmitter
  }
  processor: Data Processor {
    storage: Storage {
      shape: cylinder
      style.multiple: true
    }
  }
  jupyterlab: JupyterLab {
    pythonKernel
    juliaKernel
    bashKernel
  }
  portal: Online Portal {
    UI
  }

  tower.transmitter -> processor: phone logs
}

languages: Programming Languages {
  python
  julia
}

server: API Server

user -> workflow.tower: Make call
workflow.processor -> server
workflow.processor -> server
workflow.processor -> server

server -> data
server -> data
# server -> logs: persist

server -> workflow.portal.UI: display
user -> workflow.portal.UI: access {
  style.stroke-dash: 3
}
