name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  Jupyenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup
        uses: ./.github/actions/common-setup
        with:
          SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Example
        run: |
          nix develop ./nix/std -c just jupyterlab example build

  Quarto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup
        uses: ./.github/actions/common-setup
        with:
          SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render Quarto
        run: |
          nix develop ./nix/std -c just quarto example render

      - name: Deploy Github-Page
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: github-page
          folder: ./notebook/publish

  OCI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup
        uses: ./.github/actions/common-setup
        with:
          SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: copy oci-image to the register
        run: |
          nix run ./nix/std#x86_64-linux.repo.containers.dev.out.copyToRegistry
