name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  Jupyenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup
        uses: ./.github/actions/common-setup
        with:
          SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Example
        run: |
          nix develop ./nix/std -c just jupyterlab example build

  Quarto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup
        uses: ./.github/actions/common-setup
        with:
          SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render Quarto
        run: |
          nix develop ./nix/std -c just quarto example render

      - name: Deploy Github-Page
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: github-page
          folder: ./notebook/publish

  OCI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup
        uses: ./.github/actions/common-setup
        with:
          SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: build oci-image
        run: |
          nix build ./nix/std#x86_64-linux.repo.containers.dev.out
      - name: copy oci-image to the register
        run: |
          nix run ./nix/std#x86_64-linux.repo.containers.dev.out.copyToRegistry
          # nix run ./nix/std\#x86_64-linux.repo.containers.dev.out.copyTo -- docker://ghcr.io/hardenedlinux/aisecurity-research-template:latest
